/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.10.2/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    id("java")
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)


    implementation("io.netty:netty-all:4.1.99.Final")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}
application {
    // Define the main class for the application.
    mainClass.set("org.example.NettyServer")
}
tasks.register<JavaExec>("runServer") {
    group = "application"
    description = "Runs the Netty server"
    classpath = sourceSets["main"].runtimeClasspath
    mainClass.set("org.example.NettyServer")
}

tasks.named<JavaExec>("run") {
    mainClass.set("org.example.NettyServer")
}


